### ISSUE TITLE
Docker-compose own tmate + named session

### ISSUE THREAD

**Issue by AmarOk1412** [tmate-io/tmate#309]
Hi,
I'm trying to get a tmate server running on AWS EC2

Here is my compose (NOTE: example.com is a AWS endpoint in real config):

```
version: '3.8'

services:
  tmate-ssh-server:
    image: tmate/tmate-ssh-server:latest
    container_name: tmate-ssh-server
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    ports:
      - "2223:2223"
    environment:
      WEBSOCKET_HOSTNAME: tmate-websocket
      SSH_KEYS_PATH: "/etc/tmate-keys"
      SSH_HOSTNAME: example.com
      SSH_PORT_LISTEN: 2223
    volumes:
      - /home/ubuntu/keys:/etc/tmate-keys
      - unix-sockets:/tmp/tmate/sessions
    networks:
      - bridge

  tmate-websocket:
    image: tmate/tmate-websocket:latest
    container_name: tmate-websocket
    restart: unless-stopped
    environment:
      DAEMON_HMAC_KEY: VlCkxXLjzaFravvNSPpOdoAffaQHRNVHeSBNWUcfLDYTYHuaYQsWwyCjrSJAJUSr
      VIRTUAL_HOST: example.com
      VIRTUAL_PORT: 4001
      WEBSOCKET_BASE_URL: wss://example.com/
      ERL_NODE_NAME: example.com
      ERL_COOKIE: myerlcookie
    volumes:
      - unix-sockets:/tmp/tmate/sessions
    networks:
      - bridge

volumes:
  ssh-keys:
  unix-sockets:

networks:
  bridge:
    driver: bridge

```

(Based on https://github.com/tmate-io/tmate-kube)

Then .tmate.conf (btw, does it take /etc/tmate/tmate.conf?)

```
set -g tmate-server-host example.com
set -g tmate-server-port 2223
set -g tmate-server-rsa-fingerprint SHA256:D/2qXXXXXXXXXXXX
set -g tmate-server-ed25519-fingerprint SHA256:zbZXXXXXXXXXXXXXXXXXXXXXXXX
```

However, when client tries to do a connection (`tmate -n VM-TEST`), I have:

```

tmate-ssh-server    | [WvJa...] Spawning daemon ip=y.y.y.y
tmate-ssh-server    | [WvJa...] tmate version=2.4.0, protocol=6
tmate-ssh-server    | [WvJa...] sysname=Linux machine=x86_64 release=5.15.0-124-generic version=#134~20.04.1-Ubuntu SMP Tue Oct 1 15:27:33 UTC 2024 nodename=VM-TEST
tmate-websocket     | token=[WvJa...] id=57d3978e-978a-11ef-a20b-0242ac120002 [info] Session started stoken=WvJa... stoken_ro=ro-c33d... ssh_only=false foreground=false named=false
```

Seems  named is false (and I can't connect with a named session)

Did I miss something?
